version: '3.8'

services:

  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssword123
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    networks:
      - "reservation_network"


  web-app:
    image: web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - "reservation_network"


  react-app:
    build:
      context: ../front_end/react_app
    image: react-app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - "reservation_network"

volumes:
  mysql:
networks:
  reservation_network:

